### ISSUE TITLE
Add non-blocking functionality

### ISSUE THREAD

**Issue by GenericNerd** [phip1611/ttfb#47]
Currently, the library is not non-blocking and causes errors with tokio as a runtime is being created during execution. This could potentially be resolved through spawning the DNS portion with a call to `tokio::task::spawn_blocking`

**Comment by phip1611** [comment]
Which errors do occur inside a tokio runtime?

My time currently is limited, so I can't promise anything right away

**Comment by GenericNerd** [comment]
> Which errors do occur inside a tokio runtime?
> 
> My time currently is limited, so I can't promise anything right away

It shows that another runtime cannot be started, I don't have the exact error to hand, but it happens in the DNS portion

**Comment by phip1611** [comment]
Fixing it in 0883c59b6d8fee64ce9b2d4d44c97aa2353f3d59 / #48

**Comment by phip1611** [comment]
Will be released soon in v1.11

**Comment by phip1611** [comment]
Its released on crates.io and on nixpkgs
